### ISSUE TITLE
Global brightness modifier doesn't work

### ISSUE THREAD

**Issue by bozol** [Aytackydln/Aurora#9]
### Expected Behaviour
Global brightness modifier slider should darken the keyboard and the peripheral.

### Actual Behaviour
While keyboard britghtness modifier and peripheral brightness modifier slider individually both work, the global brightness modifier does nothing.

### Reproduction steps
Move the global britghtness modifier.

### Frequency
Everytime.

### Aurora Version:
V1

### Previously an Issue?
Yes.

**Comment by Aytackydln** [comment]
fixed in the latest version
